liip_imagine:
    driver: "gd"

    filter_sets:
        ub_avatar_sm:
            quality: 90
            filters:
                thumbnail: { size: [45, 45], mode: outbound }

        ub_avatar_md:
            quality: 90
            filters:
                thumbnail: { size: [90, 90], mode: outbound }

        ub_avatar_lg:
            quality: 90
            filters:
                thumbnail: { size: [180, 180], mode: outbound }